name: speech_emotion_recognition_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.9
  flutter_bloc: ^8.1.3
  dio: ^5.2.1+1
  shared_preferences: ^2.1.1
  flutter_screenutil: ^5.7.0
  syncfusion_flutter_charts: ^24.1.43+1
  curved_navigation_bar: ^1.0.3
  record: ^5.0.4
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  lottie: ^2.7.0
  custom_timer: ^0.2.3
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.7
  url_launcher: ^6.2.4
  dateofbirth: ^0.0.5
  fluttertoast: ^8.2.4
  internet_connection_checker: ^1.0.0+1
  flutter_offline: ^2.1.0
  animated_text_kit: ^4.2.2
  assets_audio_player: ^3.1.1
  flutter_toggle_tab: ^1.4.1
  ai_barcode_scanner: ^3.4.3
  pretty_qr_code: ^3.3.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/lotties/emotions/
    - assets/voice_over/en/
